# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'My_try.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(1000, 750)
        Ui_MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 在这里只能设置背景色为单一颜色，不能自定义图片，问题未解决
        # Ui_MainWindow.setStyleSheet("font: bold; background-color: rgb(131,175,155)")

        # Ui_MainWindow.setStyleSheet("background-image:url(E:/14581231224205443.png.jpg)")
        # Ui_MainWindow.setStyleSheet("#MainWindow{border-image:url(E:/14581231224205443.png);}")
        # Ui_MainWindow.setStyleSheet("background: redlinear-gradient(to right, rgb(0, 255, 0), rgb(0, 255, 0))")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(550, 200, 261, 191))
        self.labelResult.setMinimumSize(QtCore.QSize(150, 150))
        self.labelResult.setObjectName("labelResult")
        self.btnOpenCamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenCamera.setEnabled(True)
        self.btnOpenCamera.setGeometry(QtCore.QRect(402, 20, 111, 28))
        self.btnOpenCamera.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setEnabled(True)
        self.labelCamera.setGeometry(QtCore.QRect(10, 10, 371, 371))
        self.labelCamera.setMinimumSize(QtCore.QSize(150, 150))
        self.labelCamera.setMaximumSize(QtCore.QSize(500, 500))
        self.labelCamera.setObjectName("labelCamera")
        self.btnCapture = QtWidgets.QPushButton(self.centralwidget)
        self.btnCapture.setGeometry(QtCore.QRect(410, 100, 93, 28))
        self.btnCapture.setObjectName("btnCapture")
        self.btnGray = QtWidgets.QPushButton(self.centralwidget)
        self.btnGray.setGeometry(QtCore.QRect(410, 230, 93, 28))
        self.btnGray.setObjectName("btnGray")
        self.btnThreshold = QtWidgets.QPushButton(self.centralwidget)
        self.btnThreshold.setGeometry(QtCore.QRect(410, 270, 93, 28))
        self.btnThreshold.setObjectName("btnThreshold")
        self.btnReadImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnReadImage.setGeometry(QtCore.QRect(402, 50, 111, 28))
        self.btnReadImage.setObjectName("btnReadImage")
        self.labelCapture = QtWidgets.QLabel(self.centralwidget)
        self.labelCapture.setGeometry(QtCore.QRect(550, 10, 261, 191))
        self.labelCapture.setObjectName("labelCapture")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 420, 880, 301))
        self.groupBox.setObjectName("groupBox")
        self.labelCapture_Face = QtWidgets.QLabel(self.groupBox)
        self.labelCapture_Face.setGeometry(QtCore.QRect(10, 30, 311, 241))
        self.labelCapture_Face.setObjectName("labelCapture_Face")
        self.Analyse = QtWidgets.QGroupBox(self.groupBox)
        self.Analyse.setGeometry(QtCore.QRect(330, 70, 421, 221))
        self.Analyse.setObjectName("Analyse")
        self.btnAge = QtWidgets.QPushButton(self.Analyse)
        self.btnAge.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.btnAge.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btnAge.setObjectName("btnAge")
        self.btnSex = QtWidgets.QPushButton(self.Analyse)
        self.btnSex.setGeometry(QtCore.QRect(20, 60, 93, 28))
        self.btnSex.setObjectName("btnSex")
        self.btnEmotion = QtWidgets.QPushButton(self.Analyse)
        self.btnEmotion.setGeometry(QtCore.QRect(20, 90, 93, 28))
        self.btnEmotion.setObjectName("btnEmotion")
        self.label_age = QtWidgets.QLabel(self.Analyse)
        self.label_age.setGeometry(QtCore.QRect(120, 40, 72, 16))
        self.label_age.setObjectName("label_age")
        self.label_sex = QtWidgets.QLabel(self.Analyse)
        self.label_sex.setGeometry(QtCore.QRect(120, 70, 72, 16))
        self.label_sex.setObjectName("label_sex")
        self.label_emotion = QtWidgets.QLabel(self.Analyse)
        self.label_emotion.setGeometry(QtCore.QRect(120, 100, 72, 16))
        self.label_emotion.setObjectName("label_emotion")
        self.btnSmile = QtWidgets.QPushButton(self.Analyse)
        self.btnSmile.setGeometry(QtCore.QRect(20, 120, 93, 28))
        self.btnSmile.setObjectName("btnSmile")
        self.label_smileValue = QtWidgets.QLabel(self.Analyse)
        self.label_smileValue.setGeometry(QtCore.QRect(120, 130, 91, 16))
        self.label_smileValue.setObjectName("label_smileValue")
        self.btnRotate = QtWidgets.QPushButton(self.Analyse)
        self.btnRotate.setGeometry(QtCore.QRect(20, 170, 93, 28))
        self.btnRotate.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btnRotate.setObjectName("btnRotate")
        self.btnDetectFace = QtWidgets.QPushButton(self.groupBox)
        self.btnDetectFace.setGeometry(QtCore.QRect(340, 20, 131, 28))
        self.btnDetectFace.setObjectName("btnDetectFace")
        self.label_faceCount = QtWidgets.QLabel(self.groupBox)
        self.label_faceCount.setGeometry(QtCore.QRect(480, 20, 211, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_faceCount.setFont(font)
        self.label_faceCount.setText("")
        self.label_faceCount.setObjectName("label_faceCount")
        self.labelHough = QtWidgets.QLabel(self.groupBox)
        self.labelHough.setGeometry(QtCore.QRect(560, 70, 291, 221))
        self.labelHough.setMinimumSize(QtCore.QSize(150, 150))
        self.labelHough.setObjectName("labelHough")
        self.groupBox.raise_()
        self.labelCamera.raise_()
        self.labelResult.raise_()
        self.btnOpenCamera.raise_()
        self.btnCapture.raise_()
        self.btnReadImage.raise_()
        self.btnGray.raise_()
        self.btnThreshold.raise_()
        self.labelCapture.raise_()
        Ui_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 26))
        self.menubar.setObjectName("menubar")
        Ui_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_MainWindow.setStatusBar(self.statusbar)

        self.labelCamera.setStyleSheet("QLabel{background:black;}")
        self.labelCapture_Face.setStyleSheet("QLabel{background:white;}")
        # "QLabel{color:rgb(300,300,300,120);font-size:10px;font-weight:bold;font-family:宋体;}"

        self.retranslateUi(Ui_MainWindow)
        self.btnReadImage.clicked.connect(Ui_MainWindow.btnReadImage_Clicked)
        self.btnGray.clicked.connect(Ui_MainWindow.btnGray_Clicked)
        self.btnThreshold.clicked.connect(Ui_MainWindow.btnThreshHold_Clicked)
        self.btnOpenCamera.clicked.connect(Ui_MainWindow.btnOpenCamera_Clicked)
        self.btnCapture.clicked.connect(Ui_MainWindow.btnCapture_Clicked)
        self.btnAge.clicked.connect(Ui_MainWindow.btnGetAge_Clicked)
        self.btnSex.clicked.connect(Ui_MainWindow.btnGetSex_Clicked)
        self.btnEmotion.clicked.connect(Ui_MainWindow.btnGetEmotion_Clicked)
        self.btnDetectFace.clicked.connect(Ui_MainWindow.btnGetFace_Clicked)
        self.btnSmile.clicked.connect(Ui_MainWindow.btnGetSmileValue_Clicked)
        self.btnRotate.clicked.connect(Ui_MainWindow.btnRotate_Clicked)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)
        Ui_MainWindow.setTabOrder(self.btnOpenCamera, self.btnReadImage)
        Ui_MainWindow.setTabOrder(self.btnReadImage, self.btnCapture)
        Ui_MainWindow.setTabOrder(self.btnCapture, self.btnGray)
        Ui_MainWindow.setTabOrder(self.btnGray, self.btnThreshold)
        Ui_MainWindow.setTabOrder(self.btnThreshold, self.btnDetectFace)
        Ui_MainWindow.setTabOrder(self.btnDetectFace, self.btnAge)
        Ui_MainWindow.setTabOrder(self.btnAge, self.btnSex)
        Ui_MainWindow.setTabOrder(self.btnSex, self.btnEmotion)
        Ui_MainWindow.setTabOrder(self.btnEmotion, self.btnSmile)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle(_translate("Ui_MainWindow", "MainWindow"))
        self.labelResult.setText(_translate("Ui_MainWindow", "结果图"))
        self.btnOpenCamera.setText(_translate("Ui_MainWindow", "Open_Camera"))
        self.labelCamera.setText(_translate("Ui_MainWindow", "摄像头"))
        self.btnCapture.setText(_translate("Ui_MainWindow", "Capture"))
        self.btnGray.setText(_translate("Ui_MainWindow", "ToGray"))
        self.btnThreshold.setText(_translate("Ui_MainWindow", "Threshold"))
        self.btnReadImage.setText(_translate("Ui_MainWindow", "Open_Pictrue"))
        self.labelCapture.setText(_translate("Ui_MainWindow", "捕获图"))
        self.groupBox.setTitle(_translate("Ui_MainWindow", "Face"))
        self.labelCapture_Face.setText(_translate("Ui_MainWindow", "人脸检测"))
        self.Analyse.setTitle(_translate("Ui_MainWindow", "Face Analyse"))
        self.btnAge.setText(_translate("Ui_MainWindow", "Age"))
        self.btnSex.setText(_translate("Ui_MainWindow", "Sex"))
        self.btnEmotion.setText(_translate("Ui_MainWindow", "Emotion"))
        self.label_age.setText(_translate("Ui_MainWindow", "age_text"))
        self.label_sex.setText(_translate("Ui_MainWindow", "sex"))
        self.label_emotion.setText(_translate("Ui_MainWindow", "emotion"))
        self.btnSmile.setText(_translate("Ui_MainWindow", "SmileValue"))
        self.label_smileValue.setText(_translate("Ui_MainWindow", "smilevalue"))
        self.btnDetectFace.setText(_translate("Ui_MainWindow", "DetectFace"))
        self.btnRotate.setText(_translate("Ui_MainWindow", "Rotate"))
        self.labelHough.setText(_translate("Ui_MainWindow", "变换图"))
